config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'posts#index'
  scope 'posts' do
  	post '/new' => 'posts#new', as: "new_post"
  	get '/:id/edit' => 'posts#edit', as: "edit_post"
  	put '/:id' => 'posts#update', as: "update_post"
  	post '/:id/copy' => 'posts#copy', as: "copy_post"
  	delete '/:id/delete' => 'posts#destroy', as: "delete_post"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  #attr_accessor :title, :description, :author, :price
  before_save :init
  def init
  	self.title ||= "No title"
  	self.description ||= "No description"
  	self.author ||= "No author"
  	self.price ||= 0
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: [:edit, :update, :destroy]
  def index
  	@posts = Post.order(:price)
  end
  def new
  	@post = Post.new
  	if @post.save
  	  respond_to do |format|
  	    format.html{redirect_to root_path}
        flash[:notice] = "Successfully posted"
  	    format.json{}
  	  end
  	else
  	  respond_to do |format|
  	    format.html{redirect_to root_path}
  	    flash[:notice] = "failed to create a post"
  	    format.json{}
  	  end
  	end	
  end
  def edit
  end
  def update 
  	if @post.update_attributes(post_params)
  	  respond_to do |format|
        flash[:notice] = "Successfully updated"
        format.html{ redirect_to root_path}
        format.json{}
  	  end
    else
      respond_to do |format|
        flash[:notice] = "failed to update a post"
        format.html{ redirect_to root_path}
        format.json{}
      end
    end
  end

  def copy
    if params[:id]
      @post_original = Post.find(params[:id])
      @post = Post.new
      @post.title = @post_original.title
      @post.author = @post_original.author
      @post.description = @post_original.description
      @post.price = @post_original.price
      @post.save
      flash[:notice] = "Successfully copied!"
    else
      flash[:notice] = "Failed to copy!"
    end
    redirect_to root_path
  end
  def destroy
    @post.destroy
    redirect_to root_path
  end
  private
  def find_post
    @post = Post.find(params[:id])
  end
  def post_params
    params.require(:post).permit(:title, :description, :author, :price)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RspecTest</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash[:notice] %>
    <%= flash[:notice] %>
    <% end %>
  	<div>
  		<%= link_to "Create New Book", new_post_path, method: :post %>
  	</div>
    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<html>
<head>
	<title>Edit Post </title>
</head>
<body>
	<%= form_for(@post, url: update_post_path(@post.id), method: :put) do |f| %>
	Title
	<br>
	<%= f.text_field :title, placeholder: @post.title %>
	<br>
	Author
	<br>
	<%= f.text_field :author, placeholder: @post.author  %>
	<br>
	Description
	<br>
	<%= f.text_field :description, placeholder: @post.description  %>
	<br>
	Price
	<br>
	<%= f.text_field :price, placeholder: @post.price  %>
	<br>
	<%= f.submit "Update" %>
	<% end %>

</body>
</html>

app/views/posts/index.html.erb
<html>
<head>
	<title>Post lists</title>
</head>
<body>
	<% @posts.each do |post| %>

	<%= link_to edit_post_path(post) do %>
	<div>
		<%= post.title %>
		<br>
		<%= post.author %>
		<br>
		<%= post.description %>
		<br>
		$<%= post.price %>
	</div>
	<% end %>
	<%= link_to "copy", copy_post_path(post.id), method: :post %>
	<%= link_to "delete", delete_post_path(post.id), method: :delete %>
	<br>
	<% end %>

</body>
</html>